res/urls.py
from django.conf.urls import url
from . import views

app_name = 'res'

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='menu'),

    url(r'^register/$', views.signup, name='register'),

    url(r'^(?P<category_name>[a-z]+)/$', views.detail, name='detail'),
]

web/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from res import views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url('',include('django.contrib.auth.urls')),
    url(r'^res/', include('res.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) +\
              static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

res/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
from django.urls import reverse
from django.db.models.signals import post_save, pre_save
from django.dispatch import receiver



class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    mobile = models.IntegerField(blank=True)
    address = models.CharField(max_length=500, blank=True)

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


class Category(models.Model):
    category_title = models.CharField(max_length=100, unique=True)

    def __str__(self):
        return self.category_title


class Order(models.Model):
    time = models.DateTimeField(auto_now_add=True)
    total = models.IntegerField()
    created_by = models.ForeignKey(User, on_delete=models.PROTECT, related_name='orders')
    address = models.CharField(max_length=500, default=None)


class Item(models.Model):
    name = models.CharField(max_length=100, unique=True)
    details = models.CharField(max_length=1000)
    price = models.IntegerField()
    item_logo = models.FileField()
    category = models.ForeignKey(Category, related_name="items", on_delete=models.CASCADE)
    order = models.ForeignKey(Order, on_delete=models.PROTECT,related_name="orderItems", null=True, blank=True)

    def __str__(self):
        return self.name


class ItemInline(admin.TabularInline):
    model = Item


class CategoryAdmin(admin.ModelAdmin):
    inlines = [
        ItemInline,
    ]

res/forms.py
from django.contrib.auth.models import User
from django import forms
from .models import Profile
from django.contrib.auth.forms import UserCreationForm




class SignUpForm(UserCreationForm):
    #password = forms.CharField(widget=forms.PasswordInput)
    mobile = forms.IntegerField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2', 'mobile', ]

res/views.py
from django.http import Http404
from  .models import Profile, Category, Item , Order
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib.auth import authenticate , login
from django.views import generic
from django.views.generic import View
from .forms import SignUpForm


class IndexView(generic.ListView) :
    template_name = 'res/index.html'
    context_object_name = 'all_categories'

    def get_queryset(self):
        return Category.objects.all()


def detail(request, category_name):
    try:
        category = Category.objects.get(category_title = category_name)
        all_categories = Category.objects.all()
        items = category.items.all()
    except Category.DoesNotExist:
        raise Http404("Category does not exist")

    return render(request, 'res/menu.html', {'items': items,'all_categories': all_categories})


def index(request):
    if not request.user.is_authenticated():
        return render(request, 'res/login.html')
    else:
        return render(request, 'res/home.html')



def reg(request):
    return render(request, 'res/registration.html', {})





def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            user.profile.mobile = form.cleaned_data.get('mobile')
            user.save()
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=user.username, password=raw_password)
            login(request, user)
            return redirect('res:menu')
    else:
        form = SignUpForm()
    return render(request, 'res/registration.html', {'form': form})

res/templates/res/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Restaurant</title>

  <script src="js/site.js"></script>
  <link rel="stylesheet" href="{% static 'res/bootstrap/css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'res/main.css' %}">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="{% static 'res/bootstrap/js/bootstrap.min.js' %}"></script>
  <script src="{% static 'res/site.js' %}"></script>
</head>
<body>
    <header>
        <img src="{% static 'res/images/2.JPG' %}" alt="Happy Meal" width= "100% ;" height=150px ; >
    </header>

    <ul class="topnav">
        <div class="float-right">
            <li><a href="{% url 'res:register' %}">Register</a></li>
        </div>
        {% for category in all_categories %}
        <li><a href="{% url 'res:detail' category.category_title %}" >{{ category.category_title }}</a></li>
        {% endfor %}
    </ul>
    {% block section %}
    {% endblock %}
</body>
</html>

res/templates/res/home.html
{% extends 'res/base.html' %}
{% block section %}

    <section>
        <div class="container-fluid">
          <h1 style="margin: 20px 10px 10px 10px ;">Choose Items</h1>
          <div class="row" >
            <div class="col-md-8" style="background-color: #FAFAFA ;" id="menu">
              <div id="pizza_menu">
                  {% block content %}
                  {% endblock %}
              </div>
            </div>
            <div class="col-md" style="background-color: #D9FFFA; font-size:18px; text-align: left ;" id="order">
              <h1 style="margin-bottom: 10px ; text-align: center ;">Your Order</h1>
              <div class="row">
                  <div class="col-md-7" style="margin-top: 10px ;" id="selecteditems">

                  </div>
                  <div class="col-md-2" style="margin-top: 10px ;" id="pr">

                  </div>
                  <div class="col-md-3" style="margin-top: 8px ; text-align:right;" id="removebtn">

                  </div>
                  <div>
                      <p>
                        total price =
                          <span id="bill"></span>
                      </p>
                  </div>
                  <div style="text-align: center;" class="well col-sm-12">
                      <p><button class="btn btn-primary" type="submit">Finish</button></p>
                  </div>
              </div>
            </div>
          </div>
        </div>
    </section>
{% endblock %}

res/templates/res/index.html
{% extends 'res/base.html' %}
{% block section %}
<div>
    <h1>Select a Category</h1>
</div>
{% endblock %}

res/templates/res/login.html
{% extends 'res/base.html' %}
{% block section %}
<form action="{{ app_path }}" method="post" id="login-form">{% csrf_token %}
  <div class="form-row">
    {{ form.username.errors }}
    {{ form.username.label_tag }} {{ form.username }}
  </div>
  <div class="form-row">
    {{ form.password.errors }}
    {{ form.password.label_tag }} {{ form.password }}
    <input type="hidden" name="next" value="{{ next }}" />
  </div>
</form>

</div>
{% endblock %}

res/templates/res/menu.html
{% extends 'res/home.html' %}
{% block content %}

    <table class="table table-striped table-bordered" style="text-align: left ; border-color: black;">
        <thead>
            <tr style="font: bold 20px Tahoma;">
                <th style="width: 55% ;">Type</th>
                <th style="width: 15% ;"></th>
                <th style="width: 15% ;">Price</th>
                <th style="color: white; font: bold 20px Tahoma ; width: 15% ; text-shadow: 2px 2px 2px black, 0 0 25px blue, 0 0 5px darkblue;">HUNGRY !</th>
            </tr>
        </thead>
        <tbody>
            {% for item in items %}
            <tr>
                <td>
                    <h5>{{ item.name }}</h5>
                    <p>{{ item.details }}</p>
                </td>
                <td>
                    <!-- image not appearing -->
                    <img style="width: 200px ; height: 100px; " src="{{item.item_logo.url}}">
                </td>
                <td style="text-align: center; vertical-align:middle;">
                    {{ item.price }}
                </td>
                <td style="text-align: center; vertical-align:middle;" >
                    <button type="button" class="btn btn-success" style="margin: 5px ;" onclick="additem('{{ item.name }}', {{ item.price }} ) ;">Add</button>
                </td>
            </tr>
            {% endfor %}
        </tbody>
    </table>

{% endblock %}

res/templates/res/registration.html
{% extends 'res/base.html' %}
{% block section %}

<div class="container">
    <h2>Sign up</h2>
    <form action="" method="post" class="form-group">
        {% csrf_token %}
        {% for field in form %}
          <p>
            {{ field.label_tag }}<br>
              {{ user_form.as_p }}
              {{ profile_form.as_p }}
            {{ field }}
            {% if field.help_text %}
              <small style="color: grey">{{ field.help_text }}</small>
            {% endif %}
            {% for error in field.errors %}
              <p style="color: red">{{ error }}</p>
            {% endfor %}
          </p>
        {% endfor %}
        <button type="submit">Sign up</button>
    </form>
</div>
{% endblock %}